/* Generated by Cython 0.29 */

#ifndef __PYX_HAVE_API__pyfletcher__lib
#define __PYX_HAVE_API__pyfletcher__lib
#include "Python.h"
#include "lib.h"

static int (*__pyx_api_f_10pyfletcher_3lib_pyfletcher_is_usercore)(PyObject *) = 0;
#define pyfletcher_is_usercore __pyx_api_f_10pyfletcher_3lib_pyfletcher_is_usercore
static PyObject *(*__pyx_api_f_10pyfletcher_3lib_pyfletcher_wrap_usercore)(std::shared_ptr< fletcher::UserCore>  const &) = 0;
#define pyfletcher_wrap_usercore __pyx_api_f_10pyfletcher_3lib_pyfletcher_wrap_usercore
static std::shared_ptr< fletcher::UserCore>  (*__pyx_api_f_10pyfletcher_3lib_pyfletcher_unwrap_usercore)(PyObject *) = 0;
#define pyfletcher_unwrap_usercore __pyx_api_f_10pyfletcher_3lib_pyfletcher_unwrap_usercore
static int (*__pyx_api_f_10pyfletcher_3lib_pyfletcher_is_platform)(PyObject *) = 0;
#define pyfletcher_is_platform __pyx_api_f_10pyfletcher_3lib_pyfletcher_is_platform
static PyObject *(*__pyx_api_f_10pyfletcher_3lib_pyfletcher_wrap_platform)(std::shared_ptr< fletcher::Platform>  const &) = 0;
#define pyfletcher_wrap_platform __pyx_api_f_10pyfletcher_3lib_pyfletcher_wrap_platform
static std::shared_ptr< fletcher::Platform>  (*__pyx_api_f_10pyfletcher_3lib_pyfletcher_unwrap_platform)(PyObject *) = 0;
#define pyfletcher_unwrap_platform __pyx_api_f_10pyfletcher_3lib_pyfletcher_unwrap_platform
static int (*__pyx_api_f_10pyfletcher_3lib_pyfletcher_is_context)(PyObject *) = 0;
#define pyfletcher_is_context __pyx_api_f_10pyfletcher_3lib_pyfletcher_is_context
static PyObject *(*__pyx_api_f_10pyfletcher_3lib_pyfletcher_wrap_context)(std::shared_ptr< fletcher::Context>  const &) = 0;
#define pyfletcher_wrap_context __pyx_api_f_10pyfletcher_3lib_pyfletcher_wrap_context
static std::shared_ptr< fletcher::Context>  (*__pyx_api_f_10pyfletcher_3lib_pyfletcher_unwrap_context)(PyObject *) = 0;
#define pyfletcher_unwrap_context __pyx_api_f_10pyfletcher_3lib_pyfletcher_unwrap_context
#if !defined(__Pyx_PyIdentifier_FromString)
#if PY_MAJOR_VERSION < 3
  #define __Pyx_PyIdentifier_FromString(s) PyString_FromString(s)
#else
  #define __Pyx_PyIdentifier_FromString(s) PyUnicode_FromString(s)
#endif
#endif

#ifndef __PYX_HAVE_RT_ImportFunction
#define __PYX_HAVE_RT_ImportFunction
static int __Pyx_ImportFunction(PyObject *module, const char *funcname, void (**f)(void), const char *sig) {
    PyObject *d = 0;
    PyObject *cobj = 0;
    union {
        void (*fp)(void);
        void *p;
    } tmp;
    d = PyObject_GetAttrString(module, (char *)"__pyx_capi__");
    if (!d)
        goto bad;
    cobj = PyDict_GetItemString(d, funcname);
    if (!cobj) {
        PyErr_Format(PyExc_ImportError,
            "%.200s does not export expected C function %.200s",
                PyModule_GetName(module), funcname);
        goto bad;
    }
#if PY_VERSION_HEX >= 0x02070000
    if (!PyCapsule_IsValid(cobj, sig)) {
        PyErr_Format(PyExc_TypeError,
            "C function %.200s.%.200s has wrong signature (expected %.500s, got %.500s)",
             PyModule_GetName(module), funcname, sig, PyCapsule_GetName(cobj));
        goto bad;
    }
    tmp.p = PyCapsule_GetPointer(cobj, sig);
#else
    {const char *desc, *s1, *s2;
    desc = (const char *)PyCObject_GetDesc(cobj);
    if (!desc)
        goto bad;
    s1 = desc; s2 = sig;
    while (*s1 != '\0' && *s1 == *s2) { s1++; s2++; }
    if (*s1 != *s2) {
        PyErr_Format(PyExc_TypeError,
            "C function %.200s.%.200s has wrong signature (expected %.500s, got %.500s)",
             PyModule_GetName(module), funcname, sig, desc);
        goto bad;
    }
    tmp.p = PyCObject_AsVoidPtr(cobj);}
#endif
    *f = tmp.fp;
    if (!(*f))
        goto bad;
    Py_DECREF(d);
    return 0;
bad:
    Py_XDECREF(d);
    return -1;
}
#endif


static int import_pyfletcher__lib(void) {
  PyObject *module = 0;
  module = PyImport_ImportModule("pyfletcher.lib");
  if (!module) goto bad;
  if (__Pyx_ImportFunction(module, "pyfletcher_is_usercore", (void (**)(void))&__pyx_api_f_10pyfletcher_3lib_pyfletcher_is_usercore, "int (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pyfletcher_wrap_usercore", (void (**)(void))&__pyx_api_f_10pyfletcher_3lib_pyfletcher_wrap_usercore, "PyObject *(std::shared_ptr< fletcher::UserCore>  const &)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pyfletcher_unwrap_usercore", (void (**)(void))&__pyx_api_f_10pyfletcher_3lib_pyfletcher_unwrap_usercore, "std::shared_ptr< fletcher::UserCore>  (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pyfletcher_is_platform", (void (**)(void))&__pyx_api_f_10pyfletcher_3lib_pyfletcher_is_platform, "int (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pyfletcher_wrap_platform", (void (**)(void))&__pyx_api_f_10pyfletcher_3lib_pyfletcher_wrap_platform, "PyObject *(std::shared_ptr< fletcher::Platform>  const &)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pyfletcher_unwrap_platform", (void (**)(void))&__pyx_api_f_10pyfletcher_3lib_pyfletcher_unwrap_platform, "std::shared_ptr< fletcher::Platform>  (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pyfletcher_is_context", (void (**)(void))&__pyx_api_f_10pyfletcher_3lib_pyfletcher_is_context, "int (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pyfletcher_wrap_context", (void (**)(void))&__pyx_api_f_10pyfletcher_3lib_pyfletcher_wrap_context, "PyObject *(std::shared_ptr< fletcher::Context>  const &)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pyfletcher_unwrap_context", (void (**)(void))&__pyx_api_f_10pyfletcher_3lib_pyfletcher_unwrap_context, "std::shared_ptr< fletcher::Context>  (PyObject *)") < 0) goto bad;
  Py_DECREF(module); module = 0;
  return 0;
  bad:
  Py_XDECREF(module);
  return -1;
}

#endif /* !__PYX_HAVE_API__pyfletcher__lib */
